# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems: [jekyll/responsive_image]

# Site settings
title: Mikbe.com
email: mikaelbrg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I publish stuff I think others can find useful.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mikbe.com" # the base hostname & protocol for your site
twitter_username: mikaelberg2k
github_username:  mikberg

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Responsive images
responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  output_path_format: images/resized/%{width}/%{basename}

  sizes:
    - width: 400
    - width: 800
    - width: 1200
    - width: 2000
